### ISSUE TITLE
Breaking default behaviour

### ISSUE THREAD

**Issue by hmenke** [pgf-tikz/pgf#869]
If there will ever be a major version update to 4.0.0 then we could think about breaking some default behaviour.  Here is a list of candidates:

- [ ] #867 Reorder matrix styles
- [ ] #870 Reset all low-level PDF parameters at every picture
- [ ] #875 `/pgf/outer sep=auto`

**Comment by hmenke** [comment]
I'm locking the conversation already at this point, because otherwise this will over time become a complete mess.
